#lang datalog

% acedgfb cdfbe gcdfa fbcad dab cefabd cdfgeb eafb cagedb ab |
% cdfeb fcadb cdfeb cdbaf

shows(v0, la).
shows(v0, lb).
shows(v0, lc).
shows(v0, le).
shows(v0, lf).
shows(v0, lg).
shows(v1, lc).
shows(v1, lf).
shows(v2, la).
shows(v2, lc).
shows(v2, ld).
shows(v2, le).
shows(v2, lg).
shows(v3, la).
shows(v3, lc).
shows(v3, ld).
shows(v3, lf).
shows(v3, lg).
shows(v4, lb).
shows(v4, lc).
shows(v4, ld).
shows(v4, le).
shows(v5, la).
shows(v5, lc).
shows(v5, ld).
shows(v5, le).
shows(v5, lg).
shows(v6, la).
shows(v6, lc).
shows(v6, ld).
shows(v6, le).
shows(v6, lf).
shows(v6, lg).
shows(v7, la).
shows(v7, lc).
shows(v7, lf).
shows(v8, la).
shows(v8, lb).
shows(v8, lc).
shows(v8, ld).
shows(v8, le).
shows(v8, lf).
shows(v8, lg).
shows(v9, la).
shows(v9, lb).
shows(v9, lc).
shows(v9, ld).
shows(v9, lf).
shows(v9, lg).

shows(M0, La).
shows(M0, Lc).
shows(M0, Le).
shows(M0, Ld).
shows(M0, Lg).
shows(M0, Lf).
shows(M0, Lb).
shows(M1, Lc).
shows(M1, Ld).
shows(M1, Lf).
shows(M1, Lb).
shows(M1, Le).
shows(M2, Lg).
shows(M2, Lc).
shows(M2, Ld).
shows(M2, Lf).
shows(M2, La).
shows(M3, Lf).
shows(M3, Lb).
shows(M3, Lc).
shows(M3, La).
shows(M3, Ld).
shows(M4, Ld).
shows(M4, La).
shows(M4, Lb).
shows(M5, Lc).
shows(M5, Le).
shows(M5, Lf).
shows(M5, La).
shows(M5, Lb).
shows(M5, Ld).
shows(M6, Lc).
shows(M6, Ld).
shows(M6, Lf).
shows(M6, Lg).
shows(M6, Le).
shows(M6, Lb).
shows(M7, Le).
shows(M7, La).
shows(M7, Lf).
shows(M7, Lb).
shows(M8, Lc).
shows(M8, La).
shows(M8, Lg).
shows(M8, Le).
shows(M8, Ld).
shows(M8, Lb).
shows(M6, La).
shows(M6, Lb).

