name: Advent of Code 2021

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8.10
    - name: Update
      run: sudo apt-get update
    - name: Install racket
      run: sudo apt-get install -y racket
    - name: Install testing stuff
      run: python -m venv venv && venv/bin/pip install -r requirements.txt
    - name: Tests
      run: venv/bin/pytest -vv
    - name: Format Tests
      run: venv/bin/black . --check
    # - name: answer to day 5
    #   run: racket 5/program.rkt 5/input.txt
    - name: answer to day 6 part ii
      run: racket 6/program.rkt 256 6/input.txt
