name: Advent of Code 2021

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8.10
    - name: Download racket
      run: wget https://download.racket-lang.org/installers/8.3/racket-8.3-x86_64-linux-cs.sh
    - name: Install racket
      run: sudo sh racket-8.3-x86_64-linux-cs.sh --unix-style --dest /usr/
    - name: find out racket version we chose
      run: racket --version
    - name: list raco packages in case something is missing
      run: raco pkg show --all
    - name: print help for this version
      run: raco pkg install --help || echo ...
    - name: install racket formatter fmt
      run: raco pkg install --deps search-auto --batch --no-docs fmt
    - name: list raco packages again
      run: raco pkg show --all
    - name: Install testing stuff
      run: python -m venv venv && venv/bin/pip install -r requirements.txt
    - name: Tests
      run: venv/bin/pytest -vv
    - name: Unit Tests - day 16
      run: raco test 16/unit.rkt
    - name: Unit Tests - day 17 might be needed in part ii
      run: raco test 17/unused/test.rkt
    - name: Format Check
      run: ./format-check.sh
    - name: practice round (day 1 from 2020)
      run: racket 00/original.rkt 00/data.txt
    - name: practice round (second attempt)
      run: racket 00/recursive.rkt 00/data.txt
    - name: day 1 part i
      run: racket 01/original.rkt 01/data.txt
    - name: day 1 part i (redo)
      run: racket 01/recursive.rkt 1 01/data.txt
    - name: day 1 part ii
      run: racket 01/recursive.rkt 1 01/data.txt
    - name: day 2 part i
      run: racket 02/program.rkt 02/input.txt
    - name: day 2 part i again
      run: racket 02/again.rkt 02/input.txt
    - name: day 2 part ii
      run: racket 02/part-ii.rkt 02/input.txt
    - name: day 3 parts i & ii
      run: racket 03/program.rkt 03/input.txt
    - name: day 4 parts i & ii
      run: racket 04/program.rkt 04/data.txt
    - name: day 6 part i racket
      run: racket 06/program.rkt 80 06/input.txt
    - name: day 6 part i python
      run: venv/bin/python 06/program.py 80 06/input.txt
    - name: day 6 part ii racket
      run: racket 06/program.rkt 256 06/input.txt
    - name: day 6 part ii python
      run: venv/bin/python 06/program.py 256 06/input.txt
    - name: day 7 part i & ii
      run: racket 07/program.rkt 07/input.txt
    - name: day 8 part i & ii
      run: racket 08/program.rkt 08/input.txt
    - name: day 9
      run: racket 09/program.rkt 09/input.txt
    - name: day 10
      run: racket 10/program.rkt 10/input.txt
    - name: day 11 part i
      run: racket 11/program.rkt 100 11/input.txt
    - name: day 11 part ii
      run: racket 11/program.rkt --predict-synchroflash 11/input.txt
    - name: day 12 part i
      run: racket 12/program.rkt i 12/input.txt
    - name: day 12 part ii
      run: racket 12/program.rkt ii 12/input.txt
    - name: day 13
      run: racket 13/program.rkt 13/input.txt | tee result-13.txt
    - uses: actions/upload-artifact@v2
      with:
        name: result-13
        path: result-13.txt
    - name: day 14 part i (racket)
      run: racket 14/program.rkt 10 14/input.txt
    - name: day 14 part i (python)
      run: venv/bin/python 14/program.py 10 14/input.txt
    - name: day 14 part ii (python)
      run: venv/bin/python 14/program.py 40 14/input.txt
    - name: day 15 part i (wrong answer)
      run: racket 15/program.rkt 15/input.txt
    - name: day 15 part i (python)
      run: venv/bin/python 15/program.py 15/input.txt
    # - name: day 15 part ii (python)
    #   run: venv/bin/python 15/program.py 15/input.txt --5x5
    # 2881 - takes almost 17 minutes
    - name: day 16 part i
      run: racket 16/program.rkt 16/input.txt --version-sum
    - name: day 16 part ii
      run: racket 16/program.rkt 16/input.txt
